run:
  concurrency: 8
  timeout: 10m
  issues-exit-code: 1
  tests: true

output:
  text:
    colors: true
    print-issued-lines: true
    print-linter-name: true

linters-settings:
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - gosec
    - govet
    - ineffassign
    - revive
    - unused

issues:
  exclude-use-default: false
  exclude-files:
    - \.pb\.go$
    - \.pb\.gw\.go$
  exclude-dirs:
    - bin
    - vendor
    - var
    - tmp
    - .cache
  exclude:
    - G104 # _ instead of err checks
    - exported func .* returns unexported type .*, which can be annoying to use
    - should have a package comment
    - don't use an underscore in package name
